name: countries
description: "A Flutter app to display a list of countries."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  auto_route: ^10.1.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
